name: Java CI with Maven

on:
  push:
    branches: [ mobile ]
  pull_request:
    branches: [ mobile ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Pull the project in to the runner
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Dsuite=android

