name: Java CI with Maven

on:
  push:
    branches: [ mobile ]
  pull_request:
    branches: [ mobile ]

jobs:
  build:
    runs-on: macos-latest

    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [ 25 ] #Google api level for example [25,23,28]
        target: [ default ]

    steps:
    - name: Pull project
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check files
      run: ls -a

    - name: Install and Run Appium Server
      run: |
          chmod +x ./scripts/RunAppiumServer.sh # install and run appium server in the background
          ./scripts/RunAppiumServer.sh

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test -Dsuite=android

#    - name: Run testing
#      run: mvn clean test -Dsuite=android
