name: Selenoid from Xotabu4 tests

on:
  push:
    branches: mfp-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check files
      run: ls -a

    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2

    - name: Run testing
      run: mvn clean test -Dsuite=web
